[package]
name = "image-worker"
version = "0.1.0"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]

[dependencies]
image = "0.10"
rustc-serialize = "0.3"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
